name: Doxygen Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@1.9.5
      with:
        doxyfile-path: ./firmware/Doxyfile
        working-directory: ./firmware/doxygen-output
        enable-latex: false
